version: '3.7'

services:

  debtangel:
    image: mickeymuis007/debt-angels
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'