version: '3.7'

services:

  debtangel:
    image: mickeymuis007/debt-angels:1.0.3(dev)
    container_name: debtangel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
      - '4202:4200'